version: '2.3'

services:

  tiny-imagenet:
    build:
      context: ./
      args:
        upstream: 2.0.0b1-gpu-py3
    container_name: trader
    networks: [sparknet]
    ports:
      - 6006:6006
    runtime: nvidia
    # Env vars are read from .env file
    volumes:
      - ${DEST_DIR}:/data
      - ${ARTIFACT_DIR}:/artifacts # Log files / model checkpoints go here
    environment:
      - CUDA_VISIBLE_DEVICES # Passthrough from .env file to expose only one GPU
      - SRC_DIR=/data/tfrecords
      - ARTIFACTS_DIR=/artifacts
