name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: tensorflow/tensorflow:2.0.0-py3

    steps:
    - uses: actions/checkout@v1

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-mock pytest-cov
        pytest --cov=tin --cov-report=xml
